version: '3'
services:
  cntnr_homework_nginx:
    image: 'nginx:latest'
    container_name: homework_nginx
    hostname: homework_nginx
    restart: always
    depends_on:
      - cntnr_homework_php
    links:
      - cntnr_homework_php
    ports:
      - '8010:80'
    volumes:
      - '../htdocs:/var/www/html'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
  cntnr_homework_php:
    build: php
    container_name: homework_php
    hostname: homework_php
    restart: always
    links:
      - cntnr_homework_mysql
      - cntnr_homework_phpmyadmin
    volumes:
      - '../htdocs:/var/www/html'
      - './php/php.ini:/usr/local/etc/php/php.ini'
    ports:
      - '8011:9000'
  cntnr_homework_mysql:
    image: 'mysql:8.0'
    container_name: homework_mysql
    hostname: homework_mysql
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - './mysql/data:/var/lib/mysql'
    ports:
      - '8012:3306'
    environment:
      MYSQL_ROOT_PASSWORD: homework_root
      MYSQL_DATABASE: homework_db
      MYSQL_USER: homework_user
      MYSQL_PASSWORD: homework_password
  cntnr_homework_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: homework_phpmyadmin
    hostname: homework_phpmyadmin
    restart: always
    depends_on:
      - cntnr_homework_mysql
    links:
      - cntnr_homework_mysql
    ports:
      - '8013:80'
    environment:
      - PMA_HOST=homework_mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=homework_root